WeTheSWEople/SWEThePeople

idb/package.json
idb/public/index.html
idb/src/App.js
idb/src/Navigation.js
idb/src/Router.js
idb/src/Splash.js
idb/src/index.js

Created navbar component and used router William added in earlier PR. Had to move BrowserRouter to encapsulate App, so that Navigation component could link to different routes.
- Pretty good example of using react router [here](https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf)
- Example code [here](https://codesandbox.io/s/vVoQVk78)
Fixes issue #24

#24 Navbar

---

idb/src/District.css
idb/src/District.js
idb/src/PoliticalParty.js
idb/src/PoliticalPartyDetails.js
idb/src/PoliticalPartyInstance.js
idb/src/Router.js
idb/src/assets/all-parties.json

- Political Parties references #66 
- Changed the political parties path to use the name of the party instead of the ID closes #58 
- Changed the color of the Libertarian Party to yellow
- Added the district index page for each state references #69 
- Fixes the displayed name of At-Large districts closing #68

Changes to Political Parties and add District index page

---

idb/src/About.js
idb/src/RepresentativeDetails.js

This PR:
- Update the nicknames on the about page to satisfy benny
- references #70

Fix the link to the political party from the representative details page

---

.gitignore
app/app.py
app/config.json
app/models.py
app/requirements.txt
app/routes.py
app/static/index.html
main.py

Set up the Restful API
References #104

Set up RESTful API

---

README.md
app/main.py
app/models.py
app/routes.py
app/static/index.html

Postgres and API Setup 
References #104

Continue API/Postgres Setup

---

app/static/index.html

References #120 
References #104

Updated API page with new endpoints

---

.travis.yml
app/app.py
app/routes.py
app/tests.py
app/util.py
idb/geckodriver.log
idb/package-lock.json

Added api unit test for other models
Added database unit tests

Added more back end unit tests

---

backend/main.py
backend/tests.py
frontend/guitests.py
frontend/index.js
frontend/tests.js

See [Piazza 267](https://piazza.com/class/jcgrhy8wgynfk?cid=267), [Piazza 278](https://piazza.com/class/jcgrhy8wgynfk?cid=278)

Added symbolic links, as required by rubric

---

frontend/src/js/Districts/DistrictGrid.js
frontend/src/js/Parties/PoliticalParty.js
frontend/src/js/Representatives/RepresentativeGrid.js

Added Pagination to districts, political parties, and representatives
References #195   
References #196    
References #197    
References #198    
References #199    
References #200    
References #201    
References #202

Added Pagination

---

frontend/src/js/Districts/DistrictGrid.js
frontend/src/js/Parties/PoliticalPartyGrid.js
frontend/src/js/Representatives/RepresentativeGrid.js

Fixed pagination bugs with the next button.

Fixed pagination bugs

---

frontend/src/js/Parties/PoliticalPartyGrid.js

raul: fixed #236, put pagination in fullwidth div

---

backend/routes.py
frontend/src/js/Search.js

- Updated searching to rank each item individually based on how many times it came up
- Do not use michael-dev that branch hates us.

Update Search to use better ranking system

---

Postman.json

Added Postman tests for our new features (filtering/searching)
Resolves parts of #194

Added Postman tests for our new features

---

frontend/src/assets/resource.json
frontend/src/js/About/About.js
frontend/src/js/Search.js
resource.json

- Updates the number of unit tests each person has written
- Changes Search to display if no results were found instead of a blank page
- Updates the URL to use api.swethepeople.me instead of the dev

Update unit test count and display no result for search

---

frontend/src/js/About/About.js

PR Resolves #278, If another user outside our SWE group adds an issue, it will no longer crash the About page.

Resolves #278, fixes bug with other users adding issues

---

backend/routes.py
frontend/src/assets/css/RepresentativeInstance.css
frontend/src/js/Districts/DistrictFilter.js
frontend/src/js/Districts/DistrictGrid.js
frontend/src/js/Representatives/RepresentativeFilter.js
frontend/src/js/Representatives/RepresentativeGrid.js
frontend/src/js/Representatives/RepresentativeInstance.js

- Fixes the alignment of rep cards on the grid
- Implements saving filters on representatives grid references #259 
- Implements saving filters on districts grid references #259 
- Closes #259

Finish saving filters on grid pages

---

makefile

Added some command to makefile to be similar to Kasra's

---

frontend/src/assets/css/District.css
frontend/src/assets/css/RepresentativeInstance.css
frontend/src/js/About/About.js
frontend/src/js/Districts/DistrictFilter.js
frontend/src/js/Districts/DistrictGrid.js
frontend/src/js/Districts/StateInstance.js
frontend/src/js/Parties/PoliticalPartyDetails.js
frontend/src/js/Parties/PoliticalPartyFilter.js
frontend/src/js/Parties/PoliticalPartyGrid.js
frontend/src/js/Parties/PoliticalPartyInstance.js
frontend/src/js/Representatives/RepresentativeFilter.js
frontend/src/js/Representatives/RepresentativeGrid.js
frontend/src/js/Search.js

In an effort of making the codebase more consistent, I have removed bootstrap classes in favor of React Bootstrap components, which we were already using in some places.
Kind of References #306

Raul dev: Remove bootstrap classes

---

frontend/src/js/Representatives/Articles.js
frontend/src/js/Representatives/Bills.js
frontend/src/js/Representatives/RepresentativeDetails.js
frontend/src/js/Representatives/RepresentativeFilter.js
frontend/src/js/Representatives/RepresentativeGrid.js
frontend/src/js/Representatives/RepresentativeInstance.js
frontend/src/js/Representatives/RepresentativeSingleInstance.js
frontend/src/js/Representatives/Representatives.js

Linted Representatives folder

---

frontend/guitests.py

Raul dev: Fixed guitests

---

.gitignore
Postman.json
frontend/geckodriver.log
frontend/src/assets/resource.json
makefile

Changed API URL to prod API URL and added WebHose database

---

frontend/src/js/Districts/DistrictGrid.jsx
frontend/src/js/Districts/DistrictInstance.jsx
frontend/src/js/Districts/Districts.jsx
frontend/src/js/Districts/StateInstance.jsx

Linted and commented second half of Districts folder
